version: "3"
services:
  web:
    build: .
    ports:
      - "5555:5000"
    volumes:
      - ./app/:/home/app/
    depends_on:
      - db
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "pass"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes: 
      - .:/var/lib/postgresql/data
    expose:
      - 5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
